### PR TITLE
Prepend click_service_url to external links

### PR DESCRIPTION
**Pull request by Justin-Holmes**
/cc @jayzes @alanpeabody

### CODE REVIEW

**Comment by Justin-Holmes** [comment]
These specs are passing for me locally so not really sure what's going on with Travis.

**Comment by alanpeabody** [comment]
@Justin-Holmes is this a caching issue maybe?

**Comment by jayzes** [comment]
@Justin-Holmes @alanpeabody looks like those lorempixel image URLs were failing on Travis for some reason - stubbing them with VCR seems to fix it up. We could also stub the `FastImage` call itself in test - that wouldn't be a bad alternative either. Not sure if either of you feel strongly about it one way vs. another.

**Comment by alanpeabody** [comment]
Makes sense I guess, and LGTM

**Comment by Justin-Holmes** [comment]
The VCR change LGTM as well.

**Pull request merged**
